{{- if .Values.autoRegister.enabled -}}
{{- if not (.Capabilities.APIVersions.Has "kyverno.io/v1") }}
  {{- fail "Kyverno is required for gitlab runner auto register" }}
{{- end }}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: sync-gitlab-runner-secret
  annotations:
    policies.kyverno.io/title: Sync Gitlab Runner Registration Secret
    policies.kyverno.io/category: Gitlab
    policies.kyverno.io/subject: Gitlab Runner Registration Secret
spec:
  generateExistingOnPolicyUpdate: true
  rules:
  - name: sync-gitlab-runner-secret
    match:
      resources:
        kinds:
        - Namespace
        selector:
          matchLabels:
             kubernetes.io/metadata.name: "{{ .Release.Namespace }}"
    generate:
      kind: Secret
      name: gitlab-gitlab-runner-secret
      namespace: {{ .Release.Namespace }}
      synchronize: true
      clone:
        namespace: gitlab
        name: gitlab-gitlab-runner-secret
{{- end }}
