{{- if and .Values.networkPolicies.enabled (ne .Release.Namespace "gitlab") }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: egress-runner-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  podSelector: 
    matchLabels:
      app: gitlab-runner   # runner needs to access kube-api to start jobs
  policyTypes:
  - Egress
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          app.kubernetes.io/name: gitlab
    - ipBlock:
        cidr: {{ .Values.networkPolicies.controlPlaneCidr }}
        {{- if eq .Values.networkPolicies.controlPlaneCidr "0.0.0.0/0" }}
        except:
        # Block requests to AWS cloud metadata IP
        - 169.254.169.254/32
        {{- end }}
{{- end }}
