{{- if and .Values.networkPolicies.enabled (ne .Release.Namespace "gitlab") }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: egress-in-namespace-{{ .Release.Name }}
  namespace: "{{ .Release.Namespace }}"
spec:
  podSelector: {} # all pods
  policyTypes:
    - Egress
  egress:
    - to:
      - podSelector: {} # all pods in namespace
{{- end }}
