{{- if and .Values.networkPolicies.enabled (ne .Release.Namespace "gitlab") }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: egress-dns-{{ .Release.Name }}
  namespace: "{{ .Release.Namespace }}"
spec:
  podSelector: {} # all pods in Release namespace
  policyTypes:
    - Egress
  egress:
    - to:
      ports:
        - port: 53
          protocol: UDP
        {{- if .Values.openshift }}  
        - port: 5353
          protocol: UDP
        {{- end }}
{{- end }}
