{{- if and .Values.networkPolicies.enabled (ne .Release.Namespace "gitlab") }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-in-namespace-{{ .Release.Name }}
  namespace: "{{ .Release.Namespace }}"
spec:
  podSelector: {} # all pods
  policyTypes:
    - Ingress
  ingress:
    - from:
      - podSelector: {} # all pods in namespace
{{- end }}
