{{ if and .Values.istio.enabled (eq .Values.istio.injection "enabled") (eq .Values.istio.mtls.mode "STRICT") .Values.monitoring.enabled }}
{{- if ne .Release.Namespace "gitlab" }}
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: metrics-exception-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  mtls:
    mode: {{ .Values.istio.mtls.mode }}
  selector:
    matchLabels:
      app: gitlab-runner
  portLevelMtls:
    "9252":
      mode: PERMISSIVE
{{- end }}
{{- end }}
